# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pathtosolution: '03-MVC/ContactApp/'
  pathtoproject: '03-MVC/ContactApp/Web'

steps:
# - script: hello world!
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(pathtosolution)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(pathtoproject)/*.csproj'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise with MSDN(581982a8-2cbb-485e-b313-4da4b27d42f1)'
    appType: 'webApp'
    WebAppName: 'contactapputa'
    packageForLinux: '$(System.DefaultWorkingDirectory)/$(pathtoproject)/**/*.zip'